<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Domain.csproj" />
    <ProjectReference Include="..\Repository\Infrastructure.csproj" />
  </ItemGroup>

</Project>
